tools: rbd_recover_tool - get_header_kv()
 - dump value to file using ceph-kvstore-tool parameter 'out'
 - decrypt the hex value with xxd
 - extend the function-call to handle values for parameter
   'seek' and 'len', retrieving only needed chunks from the hexdump

diff --git a/src/tools/rbd_recover_tool/common_h b/src/tools/rbd_recover_tool/common_h
--- a/src/tools/rbd_recover_tool/common_h
+++ b/src/tools/rbd_recover_tool/common_h
@@ -459,44 +459,58 @@ function get_header_seq()
 function get_header_kv()
 {
   local func="get_header_kv"
-  if [ "$1"x = ""x ]; then
-      #echo "$func: no prefix input"
-      exit
-  elif [ "$2"x = ""x ]; then
-      #echo "$func: no key input"
-      exit
-  elif [ "$3"x != "string"x ] && [ "$3"x != "int"x ]; then
-      #echo "$func: no valid type input, use type (string|int)"
-      exit
-  fi
-
   local prefix=$1
   local key=$2
-  local types=$3
+  local type=$3
+  local seek=$4
+  local len=$5
   local res=/tmp/kv.$$$$
-
-  ceph-kvstore-tool $kvdb_type $omap_path get $prefix $key 2>/dev/null 1>$res
-  if [ $? != 0 ]; then
-      #echo "$func: <$prefix , $key> not exists" 
+  local hexvalue
+  local value
+  
+  if [ -z $prefix ]; then
+      if [ $debug ]; then
+	  echo "$func: ceph-kvstore-tool needs a valid object prefix"
+      fi
+      exit
+  elif [ -z $key ]; then
+      if [ $debug ]; then
+	  echo "$func: ceph-kvstore-tool needs a valid key "
+      fi
+      exit
+  elif [ "$type"x != "int"x ] && [ "$type"x != "string"x ]; then
+      if [ $debug ]; then
+	  echo "$func: ceph-kvstore-tool need a valid input type (string|int)"
+      fi
       exit
   fi
 
-  if [ "$types"x = "string"x ]; then
-      local value=`cat $res |tail -n +2|head -n -1|awk -F ": " '{printf $3}'|sed -n 's/^\.\{4\}//p'`
-      echo $value
-  elif [ "$types"x = "int"x ]; then
-      local value=`cat $res |tail -n +2|head -n -1| \
-      awk '
-        BEGIN{
-          FS=":"
-        } {
-          split($2, arr, " ");
-          len=length(arr)
-          for (i=len; i>0; --i) { 
-                printf arr[i];
-          }
-        }'`
-      echo $((16#$value))
+  # values are dumped in hex (big-endian format)
+  #ceph-kvstore-tool $kvdb_type $omap_path get $prefix $key 2>/dev/null 1>$res
+  ceph-kvstore-tool $kvdb_type $omap_path get $prefix $key out $res 2>/dev/null 1>/dev/null
+  if [ $? != 0 ]; then
+      if [ $debug ]; then
+	  echo "$func: error -> ceph-kvstore-tool $kvdb_type $omap_path get $prefix $key"
+      fi
+      exit
   fi
+
+
+  if [ "$type"x = "string"x ]; then
+    # process dump: offset 4, switch next 24 octets
+    test -z $seek && seek=4;
+    test -z $len && len=24;
+    value=`xxd -seek $seek -len $len -p $res | xxd -r -p`
+  elif [ "$type"x = "int"x ]; then
+   test -z $seek && seek=0;
+   test -z $len && len=8;
+   hexvalue=`xxd -seek $seek -len $len -e -p $res`
+   value=`printf "%d" 0x$hexvalue`
+  fi
+  #if [ $debug ]; then
+  #    echo "\n[debug] $func: key: $prefix -> value: $value>"
+  #fi
   rm -f $res
+  echo $value
+  #echo $__result
 }
